### ISSUE TITLE
Fix profile dropdown !!!

### ISSUE THREAD

**Issue by AhmedMazDev** [ahmedDev20/blug#4] opened 2023-03-08 19:41 UTC
![Screenshot 2023-02-27 232532](https://user-images.githubusercontent.com/89392586/224033753-19f38682-10f5-4a2e-a549-fcee3d95480d.png)

**Comment by ahmedDev20** [comment] 2023-03-09 14:53
Thank you @AhmedMazDev  for opening this issue. 🤗
The problem is fixed now 😄

**Closed as completed by ahmedDev20** 2023-03-09 14:53 UTC
